export type Lang = 'en' | 'es';

const en = {
  meta: {
    title: 'Forger Teams — Turn internal operations into working tools',
    description: 'A separate enterprise desktop app that gives employees graphical tools and their own agents on a shared company foundation.',
    imageAlt: 'Forger Teams operational workspace',
  },
  nav: { product: 'Product', how: 'How it works', trust: 'Trust', download: 'Download', sales: 'Talk to sales', language: 'Español' },
  hero: {
    eyebrow: 'The enterprise desktop app from Forger',
    title: 'Turn internal operations into tools your team can actually use.',
    body: 'Give every employee a graphical workspace to create, run, and manage their own agents on a shared company foundation.',
    primary: 'Request a Teams demo',
    secondary: 'See how it works',
    note: 'Separate from personal Forger. Download the desktop app or talk to us about an organization-wide rollout.',
    visualLabel: 'A graphical Forger Teams operation, from input to shared result',
    map: {
      workspace: 'Operations canvas · Finance',
      status: 'Agent working',
      local: 'Employee workspace',
      team: 'Shared company layer',
      stages: [
        { key: 'input', label: 'Input', title: 'Current figures', detail: '3 sources ready', aria: 'Input: current figures from three sources are ready' },
        { key: 'agent', label: 'Employee agent', title: 'Prepare report', detail: 'Working locally', aria: 'Employee agent: preparing the report in a local workspace' },
        { key: 'approval', label: 'Human decision', title: 'Review exceptions', detail: '2 need approval', aria: 'Human approval: two exceptions need a decision' },
        { key: 'shared', label: 'Team result', title: 'Monthly report', detail: 'Ready to share', aria: 'Shared team result: monthly report is ready to share' },
      ],
    },
  },
  examples: {
    eyebrow: 'Work, made visible',
    title: 'From manual process to shared operation',
    body: 'Start with the work people already do. Turn it into a clear interface, then keep the result available to everyone who needs it.',
    labels: ['Before', 'Interface', 'Result'],
    items: [
      { tag: 'Onboarding', before: 'A checklist split across email, documents, and reminders.', interface: 'One guided workspace with owners, due dates, and approvals.', result: 'Every new hire follows the same visible path.' },
      { tag: 'Recurring reporting', before: 'People copy numbers into slides at the end of every month.', interface: 'An agent prepares the draft and flags missing or unusual inputs.', result: 'The team reviews decisions instead of rebuilding the report.' },
      { tag: 'Internal requests', before: 'Requests arrive through chat with no shared status.', interface: 'A graphical queue routes each request to the right person.', result: 'Requesters and operators can see what happens next.' },
    ],
  },
  foundation: {
    eyebrow: 'One foundation, individual control',
    title: 'Local where it matters. Shared where the team needs it.',
    body: 'Employees keep a private working space on their computer. The organization provides the shared apps, context, access, and continuity that turn individual work into an operation.',
    employee: { label: 'For each employee', title: 'A workspace that feels like theirs', points: ['Own agents and connected AI account', 'Graphical tools instead of commands', 'Clear pending actions and approvals', 'Private local work until it is shared'] },
    company: { label: 'For the company', title: 'A common operational base', points: ['Shared apps and company context', 'Roles and controlled access', 'Common processes and handoffs', 'History of important team actions'] },
  },
  how: {
    eyebrow: 'How it works',
    title: 'From an account to a shared workflow in three clear steps',
    steps: [
      { number: '01', title: 'Connect your AI account', body: 'Each person connects a supported ChatGPT, Claude, or Gemini account on their own computer.' },
      { number: '02', title: 'Turn an operation into a graphical tool', body: 'Shape the process as an interface with inputs, progress, decisions, and useful output.' },
      { number: '03', title: 'Review, approve, and share', body: 'People stay in control of important decisions before results move into shared company work.' },
    ],
    states: ['Preview', 'Approval', 'Progress', 'Recovery'],
    preview: 'Draft vendor review',
    detail: 'The agent found 3 changes and needs approval before updating the shared record.',
    approve: 'Approve changes',
    revise: 'Request changes',
  },
  providers: {
    eyebrow: 'Bring your existing AI',
    title: 'Use supported accounts your team already has',
    body: 'Employees can connect supported ChatGPT, Claude, or Gemini accounts. Availability, usage, charges, plan requirements, and limits still depend on the selected provider and the employee’s account.',
    providers: ['ChatGPT', 'Claude', 'Gemini'],
    status: 'Supported',
    note: 'Not every provider plan includes every agent capability. Task content may be sent to the provider you select when it is needed to complete that task.',
  },
  trust: {
    eyebrow: 'Clear trust boundaries',
    title: 'Know what stays local, what is shared, and when AI is involved',
    items: [
      { title: 'Provider account', body: 'Each employee connects a supported provider account from their own computer. The provider’s terms and account controls continue to apply.' },
      { title: 'Task content', body: 'Content needed for a task may be sent to the provider the employee chooses. The provider’s terms and data controls apply.' },
      { title: 'Team information', body: 'Shared information uses the organization’s team services. Local work remains in the employee’s private workspace unless it is explicitly shared.' },
      { title: 'Important actions', body: 'Forger Teams keeps a history of important team actions so authorized people can understand what happened, who acted, and when.' },
    ],
    boundaries: ['LOCAL', 'TEAM', 'AI'],
  },
  download: {
    eyebrow: 'Get the desktop app',
    title: 'Choose the right Forger Teams build',
    body: 'Download the current Forger Teams desktop release for your platform. Talk to us when you are ready to plan an organization-wide rollout.',
    detected: 'Suggested for this device',
    manual: 'Choose a platform',
    version: 'Release',
    requirements: 'Requirements',
    releaseNotes: 'Release notes',
    states: { available: 'Available', gated: 'Access required', unavailable: 'Temporarily unavailable', unsupported: 'Not supported' },
    actions: { available: 'Download now', gated: 'Request access', unavailable: 'Talk to us', unsupported: 'See other platforms' },
    messages: {
      available: 'This build is ready to download.',
      gated: 'We will confirm access and onboarding with your organization before sharing the build.',
      unavailable: 'This build is not available right now. Contact us for current options.',
      unsupported: 'Forger Teams does not currently provide a build for this platform.',
    },
  },
  contact: {
    eyebrow: 'Talk to sales',
    title: 'Tell us which operation you want to improve',
    body: 'We will review your use case and reply with a concrete next step for evaluating Forger Teams.',
    points: ['A focused conversation about one real operation', 'Clear access and platform expectations', 'No obligation to replace your existing systems'],
    fields: { name: 'Name', email: 'Work email', phone: 'Phone', company: 'Company', message: 'Which process would you like to improve?' },
    placeholders: { name: 'Your name', email: 'you@company.com', phone: '+1 555 0100', company: 'Company name', message: 'Describe the current process, who uses it, and what slows the team down.' },
    consent: 'We use this information only to respond to your Forger Teams inquiry.',
    submit: 'Send inquiry',
    sending: 'Sending…',
    success: 'Thanks. We received your inquiry and will follow up using your work email.',
    error: 'We could not send your inquiry. Your entries are still here—please wait a moment and try again.',
    rateLimited: 'We received several requests. Your entries are still here—please wait a moment before trying again.',
  },
  final: { productLabel: 'Ready to use it?', productTitle: 'Get Forger Teams for your organization.', productAction: 'Download Forger Teams', salesLabel: 'Evaluating it for your company?', salesTitle: 'Talk through the operation you want to improve.', salesAction: 'Talk to sales' },
  footer: { line: 'Operational software shaped around the people who use it.', privacy: 'Privacy', personal: 'Personal Forger', rights: 'All rights reserved.' },
};

const es: typeof en = {
  meta: {
    title: 'Forger Teams — Convierte operaciones internas en herramientas',
    description: 'Una aplicación de escritorio empresarial separada que entrega herramientas gráficas y agentes propios sobre una base común de la empresa.',
    imageAlt: 'Espacio operacional de Forger Teams',
  },
  nav: { product: 'Producto', how: 'Cómo funciona', trust: 'Confianza', download: 'Descargar', sales: 'Hablar con ventas', language: 'English' },
  hero: {
    eyebrow: 'La aplicación de escritorio de Forger para empresas',
    title: 'Convierte operaciones internas en herramientas que tu equipo realmente puede usar.',
    body: 'Entrega a cada persona un espacio gráfico para crear, ejecutar y administrar sus propios agentes sobre una base común de la empresa.',
    primary: 'Solicitar demo de Teams',
    secondary: 'Ver cómo funciona',
    note: 'Separado de Forger personal. Descarga la aplicación o conversemos sobre un despliegue para toda tu organización.',
    visualLabel: 'Una operación gráfica de Forger Teams, desde la entrada hasta el resultado compartido',
    map: {
      workspace: 'Lienzo operacional · Finanzas',
      status: 'Agente trabajando',
      local: 'Espacio de la persona',
      team: 'Base compartida de la empresa',
      stages: [
        { key: 'input', label: 'Entrada', title: 'Cifras actuales', detail: '3 fuentes listas', aria: 'Entrada: las cifras actuales de tres fuentes están listas' },
        { key: 'agent', label: 'Agente personal', title: 'Preparar reporte', detail: 'Trabajando localmente', aria: 'Agente personal: prepara el reporte en un espacio local' },
        { key: 'approval', label: 'Decisión humana', title: 'Revisar excepciones', detail: '2 requieren aprobación', aria: 'Aprobación humana: dos excepciones requieren una decisión' },
        { key: 'shared', label: 'Resultado del equipo', title: 'Reporte mensual', detail: 'Listo para compartir', aria: 'Resultado compartido: el reporte mensual está listo para compartir' },
      ],
    },
  },
  examples: {
    eyebrow: 'Trabajo visible',
    title: 'Del proceso manual a una operación compartida',
    body: 'Parte por el trabajo que las personas ya realizan. Conviértelo en una interfaz clara y deja el resultado disponible para quienes lo necesitan.',
    labels: ['Antes', 'Interfaz', 'Resultado'],
    items: [
      { tag: 'Incorporación', before: 'Una lista dividida entre correos, documentos y recordatorios.', interface: 'Un espacio guiado con responsables, fechas y aprobaciones.', result: 'Cada nueva persona sigue el mismo camino visible.' },
      { tag: 'Reportes recurrentes', before: 'Las personas copian números a presentaciones al final de cada mes.', interface: 'Un agente prepara el borrador y marca datos faltantes o inusuales.', result: 'El equipo revisa decisiones en vez de reconstruir el reporte.' },
      { tag: 'Solicitudes internas', before: 'Las solicitudes llegan por chat sin un estado común.', interface: 'Una cola gráfica dirige cada solicitud a la persona correcta.', result: 'Solicitantes y operadores ven claramente qué viene después.' },
    ],
  },
  foundation: {
    eyebrow: 'Una base común, control individual',
    title: 'Local donde importa. Compartido donde el equipo lo necesita.',
    body: 'Cada persona mantiene un espacio privado en su computador. La organización entrega las apps, el contexto, los accesos y la continuidad que convierten el trabajo individual en una operación.',
    employee: { label: 'Para cada persona', title: 'Un espacio de trabajo realmente propio', points: ['Agentes propios y cuenta de IA conectada', 'Herramientas gráficas en vez de comandos', 'Acciones pendientes y aprobaciones claras', 'Trabajo local privado hasta que se comparte'] },
    company: { label: 'Para la empresa', title: 'Una base operacional común', points: ['Apps y contexto compartidos', 'Roles y acceso controlado', 'Procesos y traspasos comunes', 'Historial de acciones importantes del equipo'] },
  },
  how: {
    eyebrow: 'Cómo funciona',
    title: 'De una cuenta a un flujo compartido en tres pasos claros',
    steps: [
      { number: '01', title: 'Conecta tu cuenta de IA', body: 'Cada persona conecta una cuenta compatible de ChatGPT, Claude o Gemini en su propio computador.' },
      { number: '02', title: 'Convierte una operación en una herramienta gráfica', body: 'Representa el proceso como una interfaz con entradas, progreso, decisiones y un resultado útil.' },
      { number: '03', title: 'Revisa, aprueba y comparte', body: 'Las personas mantienen el control de las decisiones importantes antes de compartir resultados con la empresa.' },
    ],
    states: ['Vista previa', 'Aprobación', 'Progreso', 'Recuperación'],
    preview: 'Revisión de proveedores',
    detail: 'El agente encontró 3 cambios y necesita aprobación antes de actualizar el registro compartido.',
    approve: 'Aprobar cambios',
    revise: 'Solicitar cambios',
  },
  providers: {
    eyebrow: 'Usa la IA que ya tienes',
    title: 'Conecta las cuentas compatibles que tu equipo ya usa',
    body: 'Las personas pueden conectar cuentas compatibles de ChatGPT, Claude o Gemini. La disponibilidad, el uso, los cobros, los requisitos del plan y los límites siguen dependiendo del proveedor elegido y de la cuenta de cada persona.',
    providers: ['ChatGPT', 'Claude', 'Gemini'],
    status: 'Compatible',
    note: 'No todos los planes incluyen todas las capacidades de agente. El contenido de una tarea puede enviarse al proveedor que elijas cuando sea necesario para completar esa tarea.',
  },
  trust: {
    eyebrow: 'Límites de confianza claros',
    title: 'Entiende qué queda local, qué se comparte y cuándo participa la IA',
    items: [
      { title: 'Cuenta del proveedor', body: 'Cada persona conecta una cuenta compatible desde su propio computador. Siguen aplicando los términos y controles de cuenta del proveedor.' },
      { title: 'Contenido de tareas', body: 'El contenido necesario para una tarea puede enviarse al proveedor elegido por la persona. Aplican los términos y controles de datos del proveedor.' },
      { title: 'Información del equipo', body: 'La información compartida usa los servicios del equipo de la organización. El trabajo local queda en el espacio privado de la persona salvo que se comparta explícitamente.' },
      { title: 'Acciones importantes', body: 'Forger Teams mantiene un historial de acciones importantes para que personas autorizadas entiendan qué ocurrió, quién actuó y cuándo.' },
    ],
    boundaries: ['LOCAL', 'EQUIPO', 'IA'],
  },
  download: {
    eyebrow: 'Obtén la aplicación de escritorio',
    title: 'Elige la versión correcta de Forger Teams',
    body: 'Descarga la versión actual de Forger Teams para tu plataforma. Conversemos cuando quieras planificar un despliegue para toda tu organización.',
    detected: 'Sugerida para este dispositivo',
    manual: 'Elige una plataforma',
    version: 'Versión',
    requirements: 'Requisitos',
    releaseNotes: 'Notas de versión',
    states: { available: 'Disponible', gated: 'Requiere acceso', unavailable: 'No disponible temporalmente', unsupported: 'No compatible' },
    actions: { available: 'Descargar ahora', gated: 'Solicitar acceso', unavailable: 'Hablar con nosotros', unsupported: 'Ver otras plataformas' },
    messages: {
      available: 'Esta versión está lista para descargar.',
      gated: 'Confirmaremos el acceso y la incorporación con tu organización antes de compartir la aplicación.',
      unavailable: 'Esta versión no está disponible ahora. Contáctanos para conocer las opciones actuales.',
      unsupported: 'Forger Teams actualmente no ofrece una versión para esta plataforma.',
    },
  },
  contact: {
    eyebrow: 'Habla con ventas',
    title: 'Cuéntanos qué operación quieres mejorar',
    body: 'Revisaremos tu caso y responderemos con un siguiente paso concreto para evaluar Forger Teams.',
    points: ['Una conversación enfocada en una operación real', 'Expectativas claras sobre acceso y plataforma', 'Sin obligación de reemplazar tus sistemas actuales'],
    fields: { name: 'Nombre', email: 'Email de trabajo', phone: 'Teléfono', company: 'Empresa', message: '¿Qué proceso te gustaría mejorar?' },
    placeholders: { name: 'Tu nombre', email: 'tu@empresa.com', phone: '+56 9 1234 5678', company: 'Nombre de la empresa', message: 'Describe el proceso actual, quién lo usa y qué demora al equipo.' },
    consent: 'Usamos esta información únicamente para responder tu consulta sobre Forger Teams.',
    submit: 'Enviar consulta',
    sending: 'Enviando…',
    success: 'Gracias. Recibimos tu consulta y responderemos a tu email de trabajo.',
    error: 'No pudimos enviar tu consulta. Tus datos siguen aquí; espera un momento e inténtalo nuevamente.',
    rateLimited: 'Recibimos varias solicitudes. Tus datos siguen aquí; espera un momento antes de intentarlo nuevamente.',
  },
  final: { productLabel: '¿Listo para usarlo?', productTitle: 'Obtén Forger Teams para tu organización.', productAction: 'Descargar Forger Teams', salesLabel: '¿Lo estás evaluando para tu empresa?', salesTitle: 'Conversemos sobre la operación que quieres mejorar.', salesAction: 'Hablar con ventas' },
  footer: { line: 'Software operacional creado alrededor de las personas que lo usan.', privacy: 'Privacidad', personal: 'Forger personal', rights: 'Todos los derechos reservados.' },
};

export const content = { en, es } as const;
